In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('train.csv')

In [4]:
df.head()

Severity  Safety_Score  \
0                Minor_Damage_And_Injuries     49.223744   
1                Minor_Damage_And_Injuries     62.465753   
2        Significant_Damage_And_Fatalities     63.059361   
3  Significant_Damage_And_Serious_Injuries     48.082192   
4        Significant_Damage_And_Fatalities     26.484018   

   Days_Since_Inspection  Total_Safety_Complaints  Control_Metric  \
0                     14                       22       71.285324   
1                     10                       27       72.288058   
2                     13                       16       66.362808   
3                     11                        9       74.703737   
4                     13                       25       47.948952   

   Turbulence_In_gforces  Cabin_Temperature  Accident_Type_Code  \
0               0.272118              78.04                   2   
1               0.423939              84.54                   2   
2               0.322604              78.86                   7   
3               0.337029              81.79                   3   
4               0.541140              77.16                   3   

   Max_Elevation  Violations  Adverse_Weather_Metric  Accident_ID  
0   31335.476824           3                0.424352         7570  
1   26024.711057           2                0.352350        12128  
2   39269.053927           3                0.003364         2181  
3   42771.499200           1                0.211728         5946  
4   35509.228515           2                0.176883         9054

In [45]:
df.Severity.value_counts()

Highly_Fatal_And_Damaging                  3049
Significant_Damage_And_Serious_Injuries    2729
Minor_Damage_And_Injuries                  2527
Significant_Damage_And_Fatalities          1695
Name: Severity, dtype: int64

In [5]:
dict_sev={
'Minor_Damage_And_Injuries':'0',
'Highly_Fatal_And_Damaging':'1',
'Significant_Damage_And_Serious_Injuries':'2',
'Significant_Damage_And_Fatalities':'3'
}

In [6]:
df['sev']=df['Severity'].map(dict_sev)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
Severity                   10000 non-null object
Safety_Score               10000 non-null float64
Days_Since_Inspection      10000 non-null int64
Total_Safety_Complaints    10000 non-null int64
Control_Metric             10000 non-null float64
Turbulence_In_gforces      10000 non-null float64
Cabin_Temperature          10000 non-null float64
Accident_Type_Code         10000 non-null int64
Max_Elevation              10000 non-null float64
Violations                 10000 non-null int64
Adverse_Weather_Metric     10000 non-null float64
Accident_ID                10000 non-null int64
sev                        10000 non-null object
dtypes: float64(6), int64(5), object(2)
memory usage: 1015.8+ KB


In [16]:
df.isnull().sum()

Severity                   0
Safety_Score               0
Days_Since_Inspection      0
Total_Safety_Complaints    0
Control_Metric             0
Turbulence_In_gforces      0
Cabin_Temperature          0
Accident_Type_Code         0
Max_Elevation              0
Violations                 0
Adverse_Weather_Metric     0
Accident_ID                0
sev                        0
dtype: int64

In [18]:
#df.drop('Severity',axis=1,inplace=True)

In [49]:
df.head(2)

Severity  Safety_Score  Days_Since_Inspection  \
0  Minor_Damage_And_Injuries     49.223744                     14   
1  Minor_Damage_And_Injuries     62.465753                     10   

   Total_Safety_Complaints  Control_Metric  Turbulence_In_gforces  \
0                       22       71.285324               0.272118   
1                       27       72.288058               0.423939   

   Cabin_Temperature  Accident_Type_Code  Max_Elevation  Violations  \
0              78.04                   2   31335.476824           3   
1              84.54                   2   26024.711057           2   

   Adverse_Weather_Metric  Accident_ID sev  
0                0.424352         7570   0  
1                0.352350        12128   0

In [9]:
X=df.drop(['sev','Severity'],axis=1)
y=df['sev']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [67]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [68]:
lr.fit(X_train,y_train)

C:\Users\akashmas\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\akashmas\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [69]:
lr_pred=lr.predict(X_test)

In [70]:
from sklearn.metrics import classification_report,confusion_matrix

In [71]:
lr_pred.shape

(3300,)

In [72]:
y_test.shape

(3300,)

In [73]:
print(type(lr_pred))
print(type(y_test))
# earlier lr_pred was numpy arr. converted to pandas 

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [60]:
lr_pred=pd.Series(lr_pred)

In [74]:
print(classification_report(lr_pred,y_test))

              precision    recall  f1-score   support

           0       0.65      0.56      0.60       963
           1       0.81      0.57      0.67      1411
           2       0.41      0.60      0.48       633
           3       0.16      0.29      0.20       293

   micro avg       0.55      0.55      0.55      3300
   macro avg       0.51      0.50      0.49      3300
weighted avg       0.63      0.55      0.57      3300



In [75]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [76]:
rfc.fit(X_train,y_train)

C:\Users\akashmas\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [77]:
rfc_pred=rfc.predict(X_test)

In [78]:
print(classification_report(rfc_pred,y_test))

              precision    recall  f1-score   support

           0       0.87      0.78      0.82       923
           1       0.88      0.88      0.88      1001
           2       0.83      0.88      0.85       877
           3       0.82      0.89      0.86       499

   micro avg       0.85      0.85      0.85      3300
   macro avg       0.85      0.86      0.85      3300
weighted avg       0.85      0.85      0.85      3300



In [82]:
from sklearn import svm
svmclf=svm.SVC()

In [83]:
svmclf.fit(X_train,y_train)
svmclf_pred=svmclf.predict(X_test)
print(classification_report(svmclf_pred,y_test))

C:\Users\akashmas\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.30      0.47      3300
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.30      0.30      0.30      3300
   macro avg       0.25      0.08      0.12      3300
weighted avg       1.00      0.30      0.47      3300



C:\Users\akashmas\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [84]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
knn_pred=knn.predict(X_test)
print(classification_report(knn_pred,y_test))

              precision    recall  f1-score   support

           0       0.33      0.24      0.28      1122
           1       0.36      0.31      0.34      1149
           2       0.23      0.29      0.26       736
           3       0.08      0.14      0.10       293

   micro avg       0.27      0.27      0.27      3300
   macro avg       0.25      0.25      0.24      3300
weighted avg       0.29      0.27      0.28      3300



In [86]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train, y_train) 
gnb_pred = gnb.predict(X_test) 
print(classification_report(gnb_pred,y_test))

              precision    recall  f1-score   support

           0       0.49      0.51      0.50       791
           1       0.57      0.50      0.53      1148
           2       0.50      0.44      0.47      1075
           3       0.24      0.45      0.31       286

   micro avg       0.47      0.47      0.47      3300
   macro avg       0.45      0.47      0.45      3300
weighted avg       0.50      0.47      0.48      3300



In [89]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train, y_train) 
xgb_pred = xgb.predict(X_test) 
print(classification_report(xgb_pred,y_test))

              precision    recall  f1-score   support

           0       0.85      0.72      0.78       972
           1       0.80      0.91      0.85       882
           2       0.86      0.87      0.86       919
           3       0.83      0.85      0.84       527

   micro avg       0.83      0.83      0.83      3300
   macro avg       0.83      0.84      0.83      3300
weighted avg       0.83      0.83      0.83      3300



In [117]:
import lightgbm as lgb

In [142]:
#https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py

#X_train.drop('Severity',axis=1,inplace=True)
#X_train['sev']=X_train['sev'].astype('int64')

#y_train = df_train[0]
#y_test = df_test[0]
#X_train = df_train.drop(0, axis=1)
#X_test = df_test.drop(0, axis=1)

# create dataset for lightgbm
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)

# specify your configurations as a dict
params = {
    'boosting_type': 'gbdt',
    'objective': 'multiclass',  # or regression
    'num_class':4,   # for multiclass
    #'metric': {'l2', 'l1'},   # for regression
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

print('Starting training...')
# train
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=20,
                valid_sets=lgb_eval,
                early_stopping_rounds=5)

#print('Saving model...')
# save model to file
#gbm.save_model('model.txt')

print('Starting predicting...')
# predict

gbm_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration)

Starting training...
[1]	valid_0's multi_logloss: 1.30794
Training until validation scores don't improve for 5 rounds
[2]	valid_0's multi_logloss: 1.25243
[3]	valid_0's multi_logloss: 1.20889
[4]	valid_0's multi_logloss: 1.16015
[5]	valid_0's multi_logloss: 1.11757
[6]	valid_0's multi_logloss: 1.07439
[7]	valid_0's multi_logloss: 1.04321
[8]	valid_0's multi_logloss: 1.00722
[9]	valid_0's multi_logloss: 0.981687
[10]	valid_0's multi_logloss: 0.959349
[11]	valid_0's multi_logloss: 0.928504
[12]	valid_0's multi_logloss: 0.900009
[13]	valid_0's multi_logloss: 0.876981
[14]	valid_0's multi_logloss: 0.851162
[15]	valid_0's multi_logloss: 0.829327
[16]	valid_0's multi_logloss: 0.803295
[17]	valid_0's multi_logloss: 0.779693
[18]	valid_0's multi_logloss: 0.759496
[19]	valid_0's multi_logloss: 0.738332
[20]	valid_0's multi_logloss: 0.723742
Did not meet early stopping. Best iteration is:
[20]	valid_0's multi_logloss: 0.723742
Starting predicting...


In [143]:
print(type(y_test))
print(type(y_train))
print(type(X_train))
print(type(X_test))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [144]:
#X_train.info()
#X_test.info()
y_test.values

array([0, 3, 3, ..., 2, 2, 1], dtype=int64)

In [131]:
y_test=y_test.astype('int64')
y_train=y_train.astype('int64')

In [133]:
y_train.values

array([2, 0, 0, ..., 1, 3, 2], dtype=int64)

In [145]:
print(classification_report(gbm_pred,y_test))

ValueError: Classification metrics can't handle a mix of continuous-multioutput and multiclass targets

In [146]:
gbm_pred

array([[0.39190619, 0.21159327, 0.27794084, 0.11855969],
       [0.22982688, 0.13287524, 0.1416292 , 0.49566868],
       [0.13104147, 0.21152215, 0.131676  , 0.52576038],
       ...,
       [0.15819164, 0.20725787, 0.53133446, 0.10321603],
       [0.31454134, 0.2842324 , 0.25166655, 0.1495597 ],
       [0.13613257, 0.63115365, 0.14523374, 0.08748004]])

In [147]:
from sklearn.metrics import mean_squared_error
print('The rmse of prediction is:', mean_squared_error(y_test, gbm_pred) ** 0.5)

ValueError: y_true and y_pred have different number of output (1!=4)

In [149]:
from sklearn.tree import DecisionTreeClassifier
dfc=DecisionTreeClassifier()
dfc.fit(X_train, y_train) 
dfc_pred = dfc.predict(X_test) 
print(classification_report(dfc_pred,y_test))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90       842
           1       0.91      0.91      0.91       997
           2       0.92      0.91      0.91       940
           3       0.87      0.90      0.88       521

   micro avg       0.90      0.90      0.90      3300
   macro avg       0.90      0.90      0.90      3300
weighted avg       0.90      0.90      0.90      3300



In [150]:
# so Decision Tree Classifier has worked well over others.

In [151]:
dfc_pred

array([2, 3, 3, ..., 2, 2, 1], dtype=int64)

# AutoML

In [18]:
print(tpot.score(X_test, y_test))

0.0


In [23]:
from tpot import TPOTClassifier
tpot = TPOTClassifier(verbosity=2, max_time_mins=15)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))


15.25 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(input_matrix, bootstrap=True, criterion=gini, max_features=0.9000000000000001, min_samples_leaf=3, min_samples_split=2, n_estimators=100)
0.0


In [20]:
tpot.fitted_pipeline_

Pipeline(memory=None,
         steps=[('gradientboostingclassifier',
                 GradientBoostingClassifier(ccp_alpha=0.0,
                                            criterion='friedman_mse', init=None,
                                            learning_rate=0.5, loss='deviance',
                                            max_depth=10,
                                            max_features=0.9000000000000001,
                                            max_leaf_nodes=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=15,
                                            min_samples_split=7,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100,
                                            n_iter_no_change=None,
                                      

In [21]:
print(tpot.score(X_test, y_test))

0.0


In [17]:
#tpot.export('tpot_airplane_pipeline.py')